# Change these first
owner: joshbeard # Your GitHub organization or username, where this repository lives
repo: jbeard-upptime # The name of this repository

sites:
  - name: joshbeard.me
    url: https://joshbeard.me
  - name: home.jbeard.dev
    url: https://home.jbeard.dev
  - name: resume
    url: https://joshbeard.me/resume/
  - name: gemini-jbeard.co
    url: jbeard.co
    port: 1965
    check: "tcp-ping"
  - name: gopher-jbeard.co
    url: jbeard.co
    port: 70
    check: "tcp-ping"
  - name: finger-jbeard.co
    url: jbeard.co
    port: 79
    check: "tcp-ping"
  - name: jbeard.co
    url: https://jbeard.co
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: jbeard.org
    url: https://jbeard.org
  - name: jbeard.dev
    url: https://jbeard.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.jbeard.dev
  baseUrl: /jbeard-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JBeard Status
  introTitle: "Status of Josh Beard's Sites"
  introMessage: This is a status page which uses **real-time** data from my [Upptime GitHub repository](https://github.com/joshbeard/jbeard-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: joshbeard.me
      href: https://joshbeard.me

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
